rules:
  indent:
    - 2
    - 2
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - never
  no-console: 0
  prefer-arrow-callback: 0
  func-names: 0
  no-param-reassign: [2, { props: false }]
  max-len: 0 # setted in jscs

env:
  es6: true
  node: true
  jasmine: true
  protractor: true

globals:
  module: false
  require: false
  console: false

extends:
  - eslint:recommended
  - airbnb/base
parser: babel-eslint
